<?php

/**
* Implements hook_entity_presave()
*/

function myproject_custom_node_presave($node) {
  if ($node->hasField('field_birth_date')) {
    $status = $node->get('status')->getValue()[0]['value'];
    if (empty($node->get('field_birth_date')->getValue())) {
      if ($status == 1) {
        $now = new DateTime();
        $created = $now->getTimestamp();
      }
        if (!empty($created)) {
          $pub_date = gmdate('Y-m-d\TH:i:s', $created);
          $node->set('field_birth_date', $pub_date);
        }
      }
  }
}
